[package]
name = "type_lang"
version = "0.1.0"
authors = ["yui-knk <spiketeika@gmail.com>"]

[build-dependencies]
lalrpop = "*"

[dependencies]
clap = "*"
itertools = "*"
lalrpop-util = "*"
regex = "*"
